name: Pipeline (CI/CD)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        # Usando continue-on-error: true se quiser que o deploy ocorra mesmo com avisos de lint, 
        # mas o ideal é fixar os 48 erros encontrados.
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Run Unit Tests
        run: npm run test

      - name: Run E2E Tests
        run: npm run test:e2e

  deploy:
    name: Continuous Deployment
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Deploy Hook
        run: |
          curl -X GET "https://api.render.com/deploy/srv-d7tkb3favr4c73bdbpng?key=j9BlaC9ktUM"
